version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Root directory where the build.gradle file is located
    schedule:
      interval: "weekly" # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"