name: Build App

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle build cache
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build application (no tests)
        run: ./gradlew clean assemble --no-daemon