name: Deploy to Railway

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using Railway CLI
        run: npx @railway/cli up --service ${{ env.RAILWAY_SERVICE_ID }} --token ${{ env.RAILWAY_TOKEN }}