name: Deploy to Railway

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Deploy using Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}

      - name: Print Railway Service URL
        run: |
          echo $RAILWAY_SERVICE_ID