name: Deploy to Railway

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: npx @railway/cli up --service ${{ secrets.RAILWAY_SERVICE_ID }}