name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Run tests with coverage and ArchUnit checks
        run: ./gradlew test jacocoTestReport --no-daemon

      - name: Upload test report (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/test-results/test

      - name: Upload JaCoCo HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html
